# Generated by Django 6.0.6 on 2026-07-25 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0006_produto_cofins_percentual_produto_pis_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10, unique=True)),
                ('quantidade_postagens', models.PositiveIntegerField()),
                ('periodo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Configuração de Fase',
                'verbose_name_plural': 'Configurações de Fase',
            },
        ),
        migrations.CreateModel(
            name='AndamentoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia_atual', models.PositiveIntegerField(default=1)),
                ('inicio_fase', models.DateField()),
                ('fim_fase', models.DateField()),
                ('status_manual', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('descontinuado', 'Descontinuado')], default='ativo', max_length=15)),
                ('urgente', models.BooleanField(default=False)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andamento_agenda', to='produtos.produto')),
                ('fase_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_na_fase', to='agenda_videos.configuracaofase')),
            ],
            options={
                'verbose_name': 'Andamento na Agenda',
                'verbose_name_plural': 'Andamentos na Agenda',
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10)),
                ('numero_ocorrencia', models.PositiveIntegerField()),
                ('inicio_ocorrencia', models.DateField()),
                ('fim_ocorrencia', models.DateField()),
                ('status', models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('replicado', 'Replicado')], default='aguardando_aprovacao', max_length=25)),
                ('identificador_video', models.CharField(blank=True, max_length=100, null=True)),
                ('aguardando_aprovacao_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_ou_recusado_em', models.DateTimeField(blank=True, null=True)),
                ('replicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens_agenda', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoProducaoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_simples_status', models.CharField(choices=[('nao_gerado', 'Não gerado'), ('gerado', 'Gerado')], default='nao_gerado', max_length=15)),
                ('video_base_status', models.CharField(choices=[('nao_gerado', 'Não gerado'), ('gerado', 'Gerado')], default='nao_gerado', max_length=15)),
                ('roteiros_gerados', models.BooleanField(default=False)),
                ('completos_produzidos', models.BooleanField(default=False)),
                ('quantidade_roteiros', models.PositiveIntegerField(default=0)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_producao_video', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Progresso de Produção de Vídeo',
                'verbose_name_plural': 'Progressos de Produção de Vídeo',
            },
        ),
    ]
