# Generated by Django 6.0.6 on 2026-07-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamentoagenda',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='andamentoagenda',
            name='concluido_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
