# Generated by Django 6.0.6 on 2026-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0002_andamentoagenda_concluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressoproducaovideo',
            name='roteiros_insuficientes',
            field=models.BooleanField(default=False),
        ),
    ]
