# Generated by Django 6.0.6 on 2026-07-25 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0003_progressoproducaovideo_roteiros_insuficientes'),
        ('produtos', '0006_produto_cofins_percentual_produto_pis_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagio_atual', models.CharField(choices=[('nao_agendado', 'Não Agendado'), ('pronto_agendamento', 'Pronto para Agendar'), ('diaria', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('otimizado', 'Otimizado')], default='nao_agendado', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_agenda', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Roadmap da Agenda',
                'verbose_name_plural': 'Roadmaps da Agenda',
            },
        ),
    ]
