# Generated by Django 6.0.6 on 2026-07-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0004_roadmapagenda'),
        ('produtos', '0006_produto_cofins_percentual_produto_pis_percentual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressoproducaovideo',
            name='completos_produzidos',
        ),
        migrations.RemoveField(
            model_name='progressoproducaovideo',
            name='quantidade_roteiros',
        ),
        migrations.RemoveField(
            model_name='progressoproducaovideo',
            name='roteiros_gerados',
        ),
        migrations.RemoveField(
            model_name='progressoproducaovideo',
            name='roteiros_insuficientes',
        ),
        migrations.CreateModel(
            name='PreparacaoVideoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10)),
                ('roteiros_gerados', models.BooleanField(default=False)),
                ('completos_produzidos', models.BooleanField(default=False)),
                ('quantidade_roteiros', models.PositiveIntegerField(default=0)),
                ('roteiros_insuficientes', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparacoes_video', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Preparação de Vídeo por Fase',
                'verbose_name_plural': 'Preparações de Vídeo por Fase',
                'unique_together': {('produto', 'fase')},
            },
        ),
    ]
