# Generated by Django 6.0.6 on 2026-07-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0005_remove_progressoproducaovideo_completos_produzidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparacaovideofase',
            name='quantidade_roteiros',
        ),
        migrations.RemoveField(
            model_name='preparacaovideofase',
            name='roteiros_insuficientes',
        ),
    ]
