# Generated by Django 6.0.6 on 2026-07-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0006_remove_preparacaovideofase_quantidade_roteiros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamentoagenda',
            name='urgente',
        ),
        migrations.AddField(
            model_name='andamentoagenda',
            name='fim_ocorrencia_atual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapagenda',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
