# Generated by Django 6.0.6 on 2026-07-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0007_remove_andamentoagenda_urgente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapagenda',
            name='tem_video_reprovado',
            field=models.BooleanField(default=False),
        ),
    ]
