# Generated by Django 6.0.6

# Adiciona os campos de rastreio de quantidade (roteiros_quantidade_no_clique/
# completos_quantidade_no_clique) e faz backfill dos registros já marcados como
# True hoje — grava o periodo ATUAL de cada fase como se fosse a quantidade
# capturada no clique (não tem como recuperar o valor histórico real, já que
# esses campos nunca existiram antes). Ver preparacao_video_fase.py.

from django.db import migrations, models


def preencher_quantidade_legado(apps, schema_editor):
    PreparacaoVideoFase = apps.get_model('agenda_videos', 'PreparacaoVideoFase')
    ConfiguracaoFase = apps.get_model('agenda_videos', 'ConfiguracaoFase')

    periodo_por_fase = {c.fase: c.periodo for c in ConfiguracaoFase.objects.all()}

    for preparacao in PreparacaoVideoFase.objects.all():
        periodo_atual = periodo_por_fase.get(preparacao.fase)
        if periodo_atual is None:
            continue  # fase sem ConfiguracaoFase ainda — nada pra assumir

        alterou = False
        if preparacao.roteiros_gerados and preparacao.roteiros_quantidade_no_clique is None:
            preparacao.roteiros_quantidade_no_clique = periodo_atual
            alterou = True
        if preparacao.completos_produzidos and preparacao.completos_quantidade_no_clique is None:
            preparacao.completos_quantidade_no_clique = periodo_atual
            alterou = True

        if alterou:
            preparacao.save(update_fields=['roteiros_quantidade_no_clique', 'completos_quantidade_no_clique'])


def reverter_quantidade_legado(apps, schema_editor):
    # * [EXPLICAÇÃO] → No-op de propósito — não existia nada antes pra restaurar,
    #                  o campo simplesmente não existia.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0008_roadmapagenda_tem_video_reprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacaovideofase',
            name='roteiros_quantidade_no_clique',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preparacaovideofase',
            name='completos_quantidade_no_clique',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(preencher_quantidade_legado, reverter_quantidade_legado),
    ]