# Generated by Django 6.0.6 on 2026-07-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0009_preparacaovideofase_quantidade_no_clique'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamentoagenda',
            name='agendado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preparacaovideofase',
            name='completos_marcado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preparacaovideofase',
            name='roteiros_marcado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressoproducaovideo',
            name='video_base_marcado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressoproducaovideo',
            name='video_simples_marcado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
