# Generated by Django 6.0.6 on 2026-07-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0010_andamentoagenda_agendado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamentoagenda',
            name='concluido_marcado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
