# Generated by Django 6.0.6 on 2026-07-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0011_andamentoagenda_concluido_marcado_em'),
        ('produtos', '0006_produto_cofins_percentual_produto_pis_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotArquivosDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_encontrada', models.BooleanField(default=False)),
                ('motivo_nao_encontrado', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivos_videos', models.JSONField(default=list)),
                ('arquivos_usados', models.JSONField(default=list)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_drive', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Snapshot de Arquivos do Drive',
                'verbose_name_plural': 'Snapshots de Arquivos do Drive',
            },
        ),
    ]
