# Generated by Django 6.0.6 on 2026-07-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0012_snapshotarquivosdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapagenda',
            name='reestruturacao_manual',
            field=models.BooleanField(default=False),
        ),
    ]
