# Generated by Django 6.0.6 on 2026-07-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0013_roadmapagenda_reestruturacao_manual'),
        ('produtos', '0006_produto_cofins_percentual_produto_pis_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoPostagemAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando_inicio', 'Aguardando você pressionar F8'), ('rodando', 'Rodando'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='aguardando_inicio', max_length=20)),
            ],
            options={
                'verbose_name': 'Execução de Postagem Automática',
                'verbose_name_plural': 'Execuções de Postagem Automática',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemExecucaoPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('baixando', 'Baixando'), ('postando', 'Postando'), ('atualizando_agenda', 'Atualizando Agenda'), ('arquivando', 'Arquivando'), ('concluido', 'Concluído'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('mensagem_erro', models.CharField(blank=True, max_length=255, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agenda_videos.execucaopostagemautomatica')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item de Execução de Postagem',
                'verbose_name_plural': 'Itens de Execução de Postagem',
                'ordering': ['ordem'],
            },
        ),
    ]
