# Generated by Django 6.0.6 on 2026-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0014_execucaopostagemautomatica_itemexecucaopostagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemexecucaopostagem',
            name='arquivando_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemexecucaopostagem',
            name='atualizando_agenda_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemexecucaopostagem',
            name='baixando_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemexecucaopostagem',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemexecucaopostagem',
            name='postando_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
