# Generated by Django 6.0.6 on 2026-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0015_itemexecucaopostagem_arquivando_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemexecucaopostagem',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('baixando', 'Baixando'), ('postando', 'Postando'), ('atualizando_agenda', 'Atualizando Agenda'), ('arquivando', 'Arquivando'), ('concluido', 'Concluído'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado'), ('ja_postado_hoje', 'Já postado hoje — pulado')], default='aguardando', max_length=20),
        ),
    ]
