# Generated by Django 6.0.6 on 2026-07-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0016_alter_itemexecucaopostagem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaopostagemautomatica',
            name='ultimo_heartbeat_agente',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
