# Generated by Django 6.0.6 on 2026-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0018_execucaoreplicacaoautomatica_itemexecucaoreplicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='mlbs_nao_encontrados',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='postagem',
            name='mlbs_replicados',
            field=models.JSONField(default=list),
        ),
    ]
