# Generated by Django 6.0.6 on 2026-08-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0019_postagem_mlbs_nao_encontrados_and_more'),
        ('produtos', '0006_produto_cofins_percentual_produto_pis_percentual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='produto',
        ),
        migrations.AlterUniqueTogether(
            name='preparacaovideofase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='preparacaovideofase',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='progressoproducaovideo',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='roadmapagenda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='configuracaofase',
            name='quantidade_postagens',
        ),
        migrations.AddField(
            model_name='configuracaofase',
            name='distancia_dias_ao_entrar_na_fase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracaofase',
            name='distancia_dias_corridos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofase',
            name='periodo_continuo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaofase',
            name='proxima_fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fases_anteriores', to='agenda_videos.configuracaofase'),
        ),
        migrations.AlterField(
            model_name='configuracaofase',
            name='fase',
            field=models.CharField(choices=[('simples', 'Simples'), ('video_mensal', 'Vídeo Mensal'), ('video_trimestral', 'Vídeo Trimestral')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracaofase',
            name='periodo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CicloVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('simples', 'Simples'), ('video_mensal', 'Vídeo Mensal'), ('video_trimestral', 'Vídeo Trimestral')], max_length=20)),
                ('numero_ocorrencia', models.PositiveIntegerField()),
                ('data_devida', models.DateField()),
                ('base_concluido_em', models.DateTimeField(blank=True, null=True)),
                ('roteiro_concluido_em', models.DateTimeField(blank=True, null=True)),
                ('completo_concluido_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('replicado', 'Replicado')], max_length=25, null=True)),
                ('aguardando_aprovacao_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_ou_recusado_em', models.DateTimeField(blank=True, null=True)),
                ('replicado_em', models.DateTimeField(blank=True, null=True)),
                ('mlbs_replicados', models.JSONField(default=list)),
                ('mlbs_nao_encontrados', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_video', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Ciclo de Vídeo',
                'verbose_name_plural': 'Ciclos de Vídeo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatusManualAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('descontinuado', 'Descontinuado')], max_length=15)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status_manual', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Histórico de Status Manual',
                'verbose_name_plural': 'Históricos de Status Manual',
                'ordering': ['-alterado_em'],
            },
        ),
        migrations.CreateModel(
            name='IndicadoresAgendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_atual', models.CharField(blank=True, default='', max_length=25)),
                ('fase_atual', models.CharField(blank=True, default='', max_length=20)),
                ('ciclo_atual_atrasado', models.BooleanField(default=False)),
                ('tem_video_reprovado', models.BooleanField(default=False)),
                ('status_manual', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('descontinuado', 'Descontinuado')], default='ativo', max_length=15)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_agenda', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Indicadores da Agenda',
                'verbose_name_plural': 'Indicadores da Agenda',
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgente', models.BooleanField(default=False)),
                ('agendado_em', models.DateTimeField(blank=True, null=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participacao_agenda', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Participação na Agenda',
                'verbose_name_plural': 'Participações na Agenda',
            },
        ),
        migrations.DeleteModel(
            name='AndamentoAgenda',
        ),
        migrations.DeleteModel(
            name='Postagem',
        ),
        migrations.DeleteModel(
            name='PreparacaoVideoFase',
        ),
        migrations.DeleteModel(
            name='ProgressoProducaoVideo',
        ),
        migrations.DeleteModel(
            name='RoadmapAgenda',
        ),
        migrations.AddConstraint(
            model_name='ciclovideo',
            constraint=models.UniqueConstraint(fields=('produto', 'fase', 'numero_ocorrencia'), name='unico_ciclo_por_ocorrencia'),
        ),
    ]
