# Generated by Django 6.0.6 on 2026-08-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0021_alter_ciclovideo_data_devida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicostatusmanualagenda',
            options={'ordering': ['-alterado_em', '-id'], 'verbose_name': 'Histórico de Status Manual', 'verbose_name_plural': 'Históricos de Status Manual'},
        ),
    ]
