# Generated by Django 6.0.6 on 2026-08-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0022_alter_historicostatusmanualagenda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclovideo',
            name='mlb_postado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
