# Generated by Django 6.0.6 on 2026-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0023_ciclovideo_mlb_postado'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotarquivosdrive',
            name='pasta_usados_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='snapshotarquivosdrive',
            name='pasta_videos_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
