# Generated by Django 6.0.6 on 2026-09-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0024_snapshotarquivosdrive_pasta_usados_id_and_more'),
        ('produtos', '0009_produto_descricao_produto_imagem_url_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoVerificacaoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando_inicio', 'Aguardando você pressionar F8'), ('rodando', 'Rodando'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='aguardando_inicio', max_length=20)),
                ('ultimo_heartbeat_agente', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Execução de Verificação de Aprovação',
                'verbose_name_plural': 'Execuções de Verificação de Aprovação',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemExecucaoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.CharField(max_length=20)),
                ('ordem', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('lendo', 'Lendo'), ('concluido', 'Concluído'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('estado_lido', models.CharField(blank=True, max_length=20, null=True)),
                ('resultado_aplicado', models.CharField(blank=True, max_length=30, null=True)),
                ('mensagem_erro', models.CharField(blank=True, max_length=255, null=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agenda_videos.execucaoverificacaoaprovacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item de Execução de Verificação',
                'verbose_name_plural': 'Itens de Execução de Verificação',
                'ordering': ['ordem'],
            },
        ),
    ]
