# Generated by Django 6.0.6 on 2026-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_videos', '0025_execucaoverificacaoaprovacao_itemexecucaoverificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemexecucaoreplicacao',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('replicando', 'Replicando'), ('concluido', 'Concluído'), ('testado_sem_click', 'Testado — não confirmado (modo teste)'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20),
        ),
    ]
