# Generated by Django 6.0.6 on 2026-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=20, unique=True)),
                ('sku', models.CharField(blank=True, max_length=30, null=True)),
                ('cod_fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('ncm', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('curva', models.CharField(blank=True, max_length=5, null=True)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
                ('estoque', models.IntegerField(default=0)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_com_boni', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('peso_cubado', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('profundidade', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('mva', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('st_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('icms_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('icms_saida_sp', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('icms_saida_media', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ipi', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pis_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('frete_cif_fob', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('cadastrado_erp_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['titulo'],
            },
        ),
    ]
