# Generated by Django 6.0.6 on 2026-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='armazenagem_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
