# Generated by Django 6.0.6 on 2026-07-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_armazenagem_planilha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='altura',
            new_name='altura_produto_sem_embalar',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='largura',
            new_name='comprimento_produto_sem_embalar',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='profundidade',
            new_name='largura_produto_sem_embalar',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='peso',
            new_name='peso_produto_sem_embalar',
        ),
        migrations.AddField(
            model_name='produto',
            name='altura_produto_apos_embalado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento_produto_apos_embalado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura_produto_apos_embalado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_produto_apos_embalado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
