# Generated by Django 6.0.6 on 2026-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_altura_produto_altura_produto_sem_embalar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura_ordenada_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento_ordenada_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura_ordenada_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
