# Generated by Django 6.0.6 on 2026-07-24 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_altura_ordenada_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cofins_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='produto',
            name='pis_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='CodigoAssociadoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('mercado_livre', 'Mercado Livre'), ('magalu', 'Magalu'), ('raia', 'Raia'), ('shopee', 'Shopee'), ('tiktok', 'TikTok Shop'), ('amazon', 'Amazon')], max_length=20)),
                ('rotulo', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_associados', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Código Associado de Produto',
                'verbose_name_plural': 'Códigos Associados de Produto',
                'unique_together': {('produto', 'marketplace', 'rotulo')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoAnuncioMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('mercado_livre', 'Mercado Livre'), ('magalu', 'Magalu'), ('raia', 'Raia'), ('shopee', 'Shopee'), ('tiktok', 'TikTok Shop'), ('amazon', 'Amazon')], max_length=20)),
                ('anunciado', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_marketplace', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Produto Anunciado em Marketplace',
                'verbose_name_plural': 'Produtos Anunciados em Marketplace',
                'unique_together': {('produto', 'marketplace')},
            },
        ),
    ]
