# Generated by Django 6.0.6 on 2026-08-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_cofins_percentual_produto_pis_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo_no_erp',
            field=models.BooleanField(default=True),
        ),
    ]
