# Generated by Django 6.0.6 on 2026-08-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_ativo_no_erp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='icms_entrada',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ipi',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='mva',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pis_cofins',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='st_valor',
        ),
    ]
