# Generated by Django 6.0.6 on 2026-08-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_produto_icms_entrada_remove_produto_ipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url_2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url_3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url_4',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url_5',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url_6',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
