# Generated by Django 6.0.6 on 2026-09-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_produto_descricao_produto_imagem_url_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cst_saida',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
