# Generated by Django 6.0.6 on 2026-09-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produto_cofins_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='comissao_media_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='comissao_media_classico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='comissao_media_classico_amostra',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='comissao_media_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='comissao_media_premium_amostra',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
