# Generated by Django 6.0.6 on 2026-07-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_afiliado_percentual', models.DecimalField(decimal_places=2, default=8, help_text='Comissão adicional paga quando a venda vem com afiliado, em %.', max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração TikTok Shop',
                'verbose_name_plural': 'Configuração TikTok Shop',
            },
        ),
        migrations.CreateModel(
            name='FreteTiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_min', models.DecimalField(decimal_places=3, max_digits=8)),
                ('peso_max', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Faixa de Frete TikTok Shop',
                'verbose_name_plural': 'Faixas de Frete TikTok Shop',
                'ordering': ['peso_min'],
            },
        ),
    ]
