# Generated by Django 6.0.6 on 2026-07-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotiktok',
            name='desconto_vitrine_percentual',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Percentual de desconto padrão da vitrine (usado só pra calcular o preço "De" decorativo) — vale pros 2 tipos, Sem e Com Afiliado.', max_digits=5),
        ),
    ]
