# Generated by Django 6.0.6 on 2026-08-10 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0006_produto_cofins_percentual_produto_pis_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostosECustosXMLEntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_nf', models.CharField(max_length=20)),
                ('data_entrada_nota', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(max_length=255)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impostos_entrada', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Impostos e Custos de Entrada (XML) do Produto',
                'verbose_name_plural': 'Impostos e Custos de Entrada (XML) dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='IcmsStEntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliquota', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reducao', models.DecimalField(decimal_places=4, max_digits=7)),
                ('impostos_e_custos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icms_st', to='impostos.impostosecustosxmlentradaproduto')),
            ],
            options={
                'verbose_name': 'ICMS ST de Entrada (XML) do Produto',
                'verbose_name_plural': 'ICMS ST de Entrada (XML) dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='IcmsRetEntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impostos_e_custos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icms_ret', to='impostos.impostosecustosxmlentradaproduto')),
            ],
            options={
                'verbose_name': 'ICMS Retido de Entrada (XML) do Produto',
                'verbose_name_plural': 'ICMS Retido de Entrada (XML) dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='IcmsEntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliquota', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cst', models.PositiveSmallIntegerField()),
                ('reducao', models.DecimalField(decimal_places=4, max_digits=7)),
                ('impostos_e_custos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icms', to='impostos.impostosecustosxmlentradaproduto')),
            ],
            options={
                'verbose_name': 'ICMS de Entrada (XML) do Produto',
                'verbose_name_plural': 'ICMS de Entrada (XML) dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='CofinsEntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliquota', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cst', models.PositiveSmallIntegerField()),
                ('reducao', models.DecimalField(decimal_places=4, max_digits=7)),
                ('impostos_e_custos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cofins', to='impostos.impostosecustosxmlentradaproduto')),
            ],
            options={
                'verbose_name': 'COFINS de Entrada (XML) do Produto',
                'verbose_name_plural': 'COFINS de Entrada (XML) dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='IpiEntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliquota', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cst', models.PositiveSmallIntegerField()),
                ('impostos_e_custos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipi', to='impostos.impostosecustosxmlentradaproduto')),
            ],
            options={
                'verbose_name': 'IPI de Entrada (XML) do Produto',
                'verbose_name_plural': 'IPI de Entrada (XML) dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='PisEntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliquota', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cst', models.PositiveSmallIntegerField()),
                ('reducao', models.DecimalField(decimal_places=4, max_digits=7)),
                ('impostos_e_custos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pis', to='impostos.impostosecustosxmlentradaproduto')),
            ],
            options={
                'verbose_name': 'PIS de Entrada (XML) do Produto',
                'verbose_name_plural': 'PIS de Entrada (XML) dos Produtos',
            },
        ),
    ]
