# Generated by Django 6.0.6 on 2026-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='quantidade_nota',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
