# Generated by Django 6.0.6 on 2026-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0002_impostosecustosxmlentradaproduto_custo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='emissao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
