# Generated by Django 6.0.6 on 2026-08-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0003_impostosecustosxmlentradaproduto_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impostosecustosxmlentradaproduto',
            name='emissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
