# Generated by Django 6.0.6 on 2026-08-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0004_alter_impostosecustosxmlentradaproduto_emissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='ncm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
