# Generated by Django 6.0.6 on 2026-08-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0005_impostosecustosxmlentradaproduto_ncm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cofinsentradaproduto',
            old_name='cst',
            new_name='cst_xml',
        ),
        migrations.RenameField(
            model_name='icmsentradaproduto',
            old_name='cst',
            new_name='cst_xml',
        ),
        migrations.RenameField(
            model_name='icmsretentradaproduto',
            old_name='base',
            new_name='base_calculo',
        ),
        migrations.RenameField(
            model_name='impostosecustosxmlentradaproduto',
            old_name='ncm',
            new_name='ncm_xml',
        ),
        migrations.RenameField(
            model_name='ipientradaproduto',
            old_name='cst',
            new_name='cst_xml',
        ),
        migrations.RenameField(
            model_name='pisentradaproduto',
            old_name='cst',
            new_name='cst_xml',
        ),
        migrations.AddField(
            model_name='cofinsentradaproduto',
            name='cst_cadastro',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icmsentradaproduto',
            name='cst_cadastro',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='ncm_cadastro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ipientradaproduto',
            name='cst_cadastro',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pisentradaproduto',
            name='cst_cadastro',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
