# Generated by Django 6.0.6 on 2026-08-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0006_rename_cst_cofinsentradaproduto_cst_xml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icmsstentradaproduto',
            name='aliquota_fcp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='icmsstentradaproduto',
            name='valor_fcp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='empresa_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
