# Generated by Django 6.0.6 on 2026-08-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0007_icmsstentradaproduto_aliquota_fcp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='cfop_cadastro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='cfop_xml',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='codigo_auxiliar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='descricao_origem_mercadoria_cadastro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='descricao_origem_mercadoria_xml',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='id_produto_sysemp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='natureza_operacao_cadastro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='tes_saida_cadastro',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
