# Generated by Django 6.0.6 on 2026-08-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0008_impostosecustosxmlentradaproduto_cfop_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='origem_mercadoria_cadastro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='origem_mercadoria_xml',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
