# Generated by Django 6.0.6 on 2026-08-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0009_impostosecustosxmlentradaproduto_origem_mercadoria_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofinsentradaproduto',
            name='cst_cadastro',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cofinsentradaproduto',
            name='cst_xml',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='icmsentradaproduto',
            name='cst_cadastro',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='icmsentradaproduto',
            name='cst_xml',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='ipientradaproduto',
            name='cst_cadastro',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ipientradaproduto',
            name='cst_xml',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='pisentradaproduto',
            name='cst_cadastro',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pisentradaproduto',
            name='cst_xml',
            field=models.CharField(max_length=3),
        ),
    ]
