# Generated by Django 6.0.6 on 2026-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0010_alter_cofinsentradaproduto_cst_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcmsNcmUf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'ICMS de Saída por NCM e UF',
                'verbose_name_plural': 'ICMS de Saída por NCM e UF',
                'ordering': ['ncm', 'uf'],
                'unique_together': {('ncm', 'uf')},
            },
        ),
    ]
