# Generated by Django 6.0.6 on 2026-09-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0011_icmsncmuf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PisCofinsNcmCst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10)),
                ('cst', models.CharField(max_length=4)),
                ('pis', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'PIS/COFINS de Saída por NCM e CST',
                'verbose_name_plural': 'PIS/COFINS de Saída por NCM e CST',
                'ordering': ['ncm', 'cst'],
                'unique_together': {('ncm', 'cst')},
            },
        ),
    ]
