# Generated by Django 5.2.6 on 2026-09-13 07:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0012_piscofinsncmcst'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcmsNcmRejeitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10, unique=True)),
                ('qtd_ufs_divergentes', models.PositiveSmallIntegerField()),
                ('qtd_eans_no_grupo', models.PositiveIntegerField()),
                ('divergencias_por_uf', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('constatado_em', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ICMS de Saída — NCM Rejeitado (Auditoria)',
                'verbose_name_plural': 'ICMS de Saída — NCMs Rejeitados (Auditoria)',
                'ordering': ['-qtd_eans_no_grupo', 'ncm'],
            },
        ),
        migrations.CreateModel(
            name='PisCofinsNcmCstRejeitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10)),
                ('cst', models.CharField(max_length=4)),
                ('qtd_eans_no_grupo', models.PositiveIntegerField()),
                ('campos_divergentes', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('constatado_em', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'PIS/COFINS de Saída — NCM+CST Rejeitado (Auditoria)',
                'verbose_name_plural': 'PIS/COFINS de Saída — NCM+CST Rejeitados (Auditoria)',
                'ordering': ['-qtd_eans_no_grupo', 'ncm', 'cst'],
                'unique_together': {('ncm', 'cst')},
            },
        ),
    ]