# Generated by Django 6.0.6 on 2026-09-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0013_icmsncmrejeitado_piscofinsncmcstrejeitado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icmsncmrejeitado',
            options={'ordering': ['-qtd_eans_no_grupo', 'ncm', 'cst', 'origem_mercadoria_cadastro'], 'verbose_name': 'ICMS de Saída — NCM Rejeitado (Auditoria)', 'verbose_name_plural': 'ICMS de Saída — NCMs Rejeitados (Auditoria)'},
        ),
        migrations.AlterModelOptions(
            name='icmsncmuf',
            options={'ordering': ['ncm', 'cst', 'origem_mercadoria_cadastro', 'uf'], 'verbose_name': 'ICMS de Saída por NCM, CST, Origem e UF', 'verbose_name_plural': 'ICMS de Saída por NCM, CST, Origem e UF'},
        ),
        migrations.AlterUniqueTogether(
            name='icmsncmuf',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='icmsncmrejeitado',
            name='cst',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icmsncmrejeitado',
            name='origem_mercadoria_cadastro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='icmsncmuf',
            name='cst',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icmsncmuf',
            name='origem_mercadoria_cadastro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='icmsncmrejeitado',
            name='ncm',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='icmsncmrejeitado',
            unique_together={('ncm', 'cst', 'origem_mercadoria_cadastro')},
        ),
        migrations.AlterUniqueTogether(
            name='icmsncmuf',
            unique_together={('ncm', 'cst', 'origem_mercadoria_cadastro', 'uf')},
        ),
    ]
