# Generated by Django 6.0.6 on 2026-09-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0014_expande_chave_icms_ncm_cst_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcmsSaidaMediaPorNcmCstOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10)),
                ('cst', models.CharField(max_length=4)),
                ('origem_mercadoria_cadastro', models.CharField(blank=True, max_length=5, null=True)),
                ('media_ponderada', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'ICMS de Saída — Média Ponderada por NCM, CST e Origem',
                'verbose_name_plural': 'ICMS de Saída — Média Ponderada por NCM, CST e Origem',
                'ordering': ['ncm', 'cst', 'origem_mercadoria_cadastro'],
                'unique_together': {('ncm', 'cst', 'origem_mercadoria_cadastro')},
            },
        ),
    ]
