# Generated by Django 6.0.6 on 2026-09-14 03:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0015_icmssaidamediaporncmcstorigem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcmsSaidaPorNcmCstOrigemRejeitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10)),
                ('cst', models.CharField(max_length=4)),
                ('origem_mercadoria_cadastro', models.CharField(blank=True, max_length=5, null=True)),
                ('qtd_ufs_divergentes', models.PositiveSmallIntegerField()),
                ('qtd_eans_no_grupo', models.PositiveIntegerField()),
                ('divergencias_por_uf', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('constatado_em', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ICMS de Saída — NCM Rejeitado (Auditoria)',
                'verbose_name_plural': 'ICMS de Saída — NCMs Rejeitados (Auditoria)',
                'ordering': ['-qtd_eans_no_grupo', 'ncm', 'cst', 'origem_mercadoria_cadastro'],
                'unique_together': {('ncm', 'cst', 'origem_mercadoria_cadastro')},
            },
        ),
        migrations.CreateModel(
            name='IcmsSaidaPorNcmCstOrigemUf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('cst', models.CharField(max_length=4)),
                ('origem_mercadoria_cadastro', models.CharField(blank=True, max_length=5, null=True)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'ICMS de Saída por NCM, CST, Origem e UF',
                'verbose_name_plural': 'ICMS de Saída por NCM, CST, Origem e UF',
                'ordering': ['ncm', 'cst', 'origem_mercadoria_cadastro', 'uf'],
                'unique_together': {('ncm', 'cst', 'origem_mercadoria_cadastro', 'uf')},
            },
        ),
        migrations.CreateModel(
            name='PisCofinsSaidaPorNcmCst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10)),
                ('cst', models.CharField(max_length=4)),
                ('pis', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'PIS/COFINS de Saída por NCM e CST',
                'verbose_name_plural': 'PIS/COFINS de Saída por NCM e CST',
                'ordering': ['ncm', 'cst'],
                'unique_together': {('ncm', 'cst')},
            },
        ),
        migrations.CreateModel(
            name='PisCofinsSaidaPorNcmCstRejeitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=10)),
                ('cst', models.CharField(max_length=4)),
                ('qtd_eans_no_grupo', models.PositiveIntegerField()),
                ('campos_divergentes', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('constatado_em', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'PIS/COFINS de Saída — NCM+CST Rejeitado (Auditoria)',
                'verbose_name_plural': 'PIS/COFINS de Saída — NCM+CST Rejeitados (Auditoria)',
                'ordering': ['-qtd_eans_no_grupo', 'ncm', 'cst'],
                'unique_together': {('ncm', 'cst')},
            },
        ),
        migrations.DeleteModel(
            name='IcmsNcmRejeitado',
        ),
        migrations.DeleteModel(
            name='IcmsNcmUf',
        ),
        migrations.DeleteModel(
            name='PisCofinsNcmCst',
        ),
        migrations.DeleteModel(
            name='PisCofinsNcmCstRejeitado',
        ),
    ]
