# Generated by Django 6.0.6 on 2026-10-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0016_icmssaidaporncmcstorigemrejeitado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=60, unique=True)),
                ('numero_nf', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(max_length=255)),
                ('empresa_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('emissao', models.DateField(blank=True, null=True)),
                ('data_entrada_nota', models.DateField(blank=True, null=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada (espelho)',
                'verbose_name_plural': 'Notas Fiscais de Entrada (espelho)',
            },
        ),
        migrations.AddField(
            model_name='impostosecustosxmlentradaproduto',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='ItemNotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('id_produto_sysemp', models.PositiveIntegerField(blank=True, null=True)),
                ('nome_produto', models.CharField(max_length=500)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('dados_brutos', models.JSONField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='impostos.notafiscalentrada')),
            ],
            options={
                'verbose_name': 'Item de Nota Fiscal de Entrada (espelho)',
                'verbose_name_plural': 'Itens de Nota Fiscal de Entrada (espelho)',
                'ordering': ['numero_item'],
                'constraints': [models.UniqueConstraint(fields=('nota', 'numero_item'), name='item_nf_entrada_unico_por_nota')],
            },
        ),
    ]
