# Generated by Django 6.0.6 on 2026-07-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplaces', '0002_alter_marketplace_options_marketplace_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeAnuncioMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('closed', 'Encerrado'), ('under_review', 'Em revisão'), ('payment_required', 'Débito pendente'), ('not_yet_active', 'Aguardando ativação')], max_length=20)),
                ('tipo_anuncio', models.CharField(choices=[('gold_special', 'Clássico'), ('gold_pro', 'Premium')], max_length=20)),
                ('tipo_logistico', models.CharField(choices=[('fulfillment', 'FULL'), ('cross_docking', 'Coleta'), ('xd_drop_off', 'Agência'), ('self_service', 'Flex Puro'), ('not_specified', 'Legado'), ('drop_off', 'Correios'), ('custom', 'Por nossa conta')], max_length=20)),
                ('classificacao_catalogo', models.CharField(choices=[('simples', 'Simples'), ('base', 'Base de Catálogo'), ('catalogo', 'Anúncio de Catálogo')], max_length=10)),
                ('flex', models.BooleanField()),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplace')),
            ],
            options={
                'verbose_name': 'Tipo de Anúncio Mercado Livre',
                'verbose_name_plural': 'Tipos de Anúncio Mercado Livre',
                'unique_together': {('marketplace', 'status', 'tipo_anuncio', 'tipo_logistico', 'classificacao_catalogo', 'flex')},
            },
        ),
    ]
