# Generated by Django 6.0.6 on 2026-07-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0001_initial'),
        ('produtos', '0002_alter_produto_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.CharField(max_length=20, unique=True)),
                ('mlbu', models.CharField(blank=True, max_length=20, null=True)),
                ('sku_ml', models.CharField(blank=True, max_length=30, null=True)),
                ('titulo_anuncio', models.CharField(blank=True, max_length=255, null=True)),
                ('catalog_product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('catalog_listing', models.BooleanField(blank=True, null=True)),
                ('item_relations', models.JSONField(blank=True, null=True)),
                ('estoque', models.IntegerField(default=0)),
                ('qtd_vendas', models.IntegerField(default=0)),
                ('permalink', models.URLField(blank=True, max_length=500, null=True)),
                ('data_criacao_ml', models.DateTimeField(blank=True, null=True)),
                ('ultima_atualizacao_ml', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_mercado_livre', to='produtos.produto', to_field='sku')),
                ('tipo_de_anuncio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to='mercado_livre.tipodeanunciomercadolivre')),
            ],
            options={
                'verbose_name': 'Anúncio Mercado Livre',
                'verbose_name_plural': 'Anúncios Mercado Livre',
                'ordering': ['mlb'],
            },
        ),
    ]
