# Generated by Django 6.0.6 on 2026-07-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0002_anunciomercadolivre'),
        ('produtos', '0002_alter_produto_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anunciomercadolivre',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='anunciomercadolivre',
            name='mlbu',
        ),
        migrations.RemoveField(
            model_name='anunciomercadolivre',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='anunciomercadolivre',
            name='qtd_vendas',
        ),
        migrations.RemoveField(
            model_name='anunciomercadolivre',
            name='sku_ml',
        ),
        migrations.CreateModel(
            name='VariacaoAnuncioMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacao_id', models.CharField(max_length=30)),
                ('sku_ml', models.CharField(blank=True, max_length=30, null=True)),
                ('estoque', models.IntegerField(default=0)),
                ('qtd_vendas', models.IntegerField(default=0)),
                ('atributos', models.CharField(blank=True, max_length=255, null=True)),
                ('num_fotos', models.IntegerField(default=0)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='mercado_livre.anunciomercadolivre')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variacoes_mercado_livre', to='produtos.produto', to_field='sku')),
            ],
            options={
                'verbose_name': 'Variação de Anúncio Mercado Livre',
                'verbose_name_plural': 'Variações de Anúncio Mercado Livre',
                'unique_together': {('anuncio', 'variacao_id')},
            },
        ),
    ]
