# Generated by Django 6.0.6 on 2026-07-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0003_remove_anunciomercadolivre_estoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=60, unique=True)),
                ('grupo', models.CharField(choices=[('UP_SHORTS', 'Clipes'), ('UP_PICTURES', 'Imagens'), ('UP_TITLE', 'Título'), ('UP_GTIN', 'Código Universal'), ('UP_TECHNICAL_SPECIFICATIONS_MAIN', 'Ficha Técnica'), ('UP_STOCK_DEPOSITO', 'Estoque'), ('UP_STOCK_AVAILABILITY_TIME', 'Prazo'), ('UP_FREE_SHIPPING', 'Frete Grátis'), ('UP_FINANCING', 'Parcelamento'), ('UP_PROMOTIONS', 'Promoções'), ('UP_PRICE', 'Preço'), ('UP_ME_FLEX_ITEM_OPTIN', 'Flex'), ('UP_SIZE_CHART', 'Tabela de Medidas'), ('UP_CATALOG', 'Catálogo')], max_length=40)),
                ('nome', models.CharField(max_length=150)),
                ('pergunta', models.CharField(max_length=150)),
                ('como_aprovar', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Critério de Qualidade',
                'verbose_name_plural': 'Critérios de Qualidade',
                'ordering': ['grupo', 'rule_key'],
            },
        ),
        migrations.CreateModel(
            name='QualidadeAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=30, null=True)),
                ('calculado_em', models.DateTimeField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anuncio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualidade', to='mercado_livre.anunciomercadolivre')),
            ],
            options={
                'verbose_name': 'Qualidade do Anúncio',
                'verbose_name_plural': 'Qualidade dos Anúncios',
            },
        ),
        migrations.CreateModel(
            name='QualidadeAnuncioCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('nao_aprovado', 'Não aprovado'), ('nao_aplicavel', 'Não aplicável')], max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('calculado_em', models.DateTimeField(blank=True, null=True)),
                ('link_correcao', models.URLField(blank=True, max_length=500, null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='mercado_livre.criterioqualidade')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='mercado_livre.qualidadeanuncio')),
            ],
            options={
                'verbose_name': 'Avaliação de Critério',
                'verbose_name_plural': 'Avaliações de Critério',
                'unique_together': {('qualidade', 'criterio')},
            },
        ),
    ]
