# Generated by Django 6.0.6 on 2026-07-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0004_criterioqualidade_qualidadeanuncio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterioqualidade',
            name='catalogado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='criterioqualidade',
            name='grupo',
            field=models.CharField(choices=[('UP_SHORTS', 'Clipes'), ('UP_PICTURES', 'Imagens'), ('UP_TITLE', 'Título'), ('UP_GTIN', 'Código Universal'), ('UP_TECHNICAL_SPECIFICATIONS_MAIN', 'Ficha Técnica'), ('UP_STOCK_DEPOSITO', 'Estoque'), ('UP_STOCK_AVAILABILITY_TIME', 'Prazo'), ('UP_FREE_SHIPPING', 'Frete Grátis'), ('UP_FINANCING', 'Parcelamento'), ('UP_PROMOTIONS', 'Promoções'), ('UP_PRICE', 'Preço'), ('UP_ME_FLEX_ITEM_OPTIN', 'Flex'), ('UP_SIZE_CHART', 'Tabela de Medidas'), ('UP_CATALOG', 'Catálogo'), ('DESCONHECIDO', 'Desconhecido — critério novo da API')], max_length=40),
        ),
    ]
