# Generated by Django 6.0.6 on 2026-07-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0006_variacaoanunciomercadolivre_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='imagem_principal_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
