# Generated by Django 6.0.6 on 2026-07-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0007_variacaoanunciomercadolivre_imagem_principal_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualidadeanuncio',
            name='anuncio',
        ),
        migrations.AddField(
            model_name='qualidadeanuncio',
            name='variacao',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qualidade', to='mercado_livre.variacaoanunciomercadolivre'),
            preserve_default=False,
        ),
    ]
