# Generated by Django 6.0.6 on 2026-07-07 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0008_remove_qualidadeanuncio_anuncio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompeticaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('winning', 'Ganhando'), ('competing', 'Perdendo'), ('sharing_first_place', 'Empatado em 1º'), ('listed', 'Inelegível'), ('not_listed', 'Fora do catálogo')], max_length=30, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to_win', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency_id', models.CharField(blank=True, max_length=10, null=True)),
                ('visit_share', models.CharField(blank=True, max_length=20, null=True)),
                ('competitors_sharing_first_place', models.IntegerField(blank=True, null=True)),
                ('consistent', models.BooleanField(blank=True, null=True)),
                ('catalog_product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('reason', models.JSONField(blank=True, null=True)),
                ('boosts', models.JSONField(blank=True, null=True)),
                ('winner', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anuncio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competicao', to='mercado_livre.anunciomercadolivre')),
            ],
            options={
                'verbose_name': 'Competição de Catálogo',
                'verbose_name_plural': 'Competições de Catálogo',
            },
        ),
    ]
