# Generated by Django 6.0.6 on 2026-07-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0009_competicaocatalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='preco_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='preco_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
