# Generated by Django 6.0.6 on 2026-07-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0010_variacaoanunciomercadolivre_preco_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciomercadolivre',
            name='eh_fossil_migracao',
            field=models.BooleanField(default=False),
        ),
    ]
