# Generated by Django 6.0.6 on 2026-07-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0011_anunciomercadolivre_eh_fossil_migracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreteML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_min', models.DecimalField(decimal_places=3, max_digits=8)),
                ('peso_max', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Frete ML',
                'verbose_name_plural': 'Fretes ML',
                'ordering': ['peso_min', 'preco_min'],
            },
        ),
    ]
