# Generated by Django 6.0.6 on 2026-07-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0012_freteml'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator_coleta', models.DecimalField(decimal_places=2, default=72, help_text='Custo de coleta em R$ por m³.', max_digits=8)),
                ('periodo_armazenagem', models.IntegerField(default=30, help_text='Dias considerados no cálculo mensal de armazenagem.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Mercado Livre',
                'verbose_name_plural': 'Configuração Mercado Livre',
            },
        ),
        migrations.CreateModel(
            name='FaixaArmazenagemMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_diario', models.DecimalField(decimal_places=4, max_digits=8)),
                ('max_altura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_largura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_profundidade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faixa de Armazenagem ML',
                'verbose_name_plural': 'Faixas de Armazenagem ML',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoTipoAnuncioMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anuncio', models.CharField(choices=[('gold_special', 'Clássico'), ('gold_pro', 'Premium')], max_length=20)),
                ('tipo_logistico', models.CharField(choices=[('fulfillment', 'FULL'), ('cross_docking', 'Coleta'), ('xd_drop_off', 'Agência'), ('self_service', 'Flex Puro'), ('not_specified', 'Legado'), ('drop_off', 'Correios'), ('custom', 'Por nossa conta')], max_length=20)),
                ('catalogo', models.BooleanField(default=False)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acrescimo_preco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margem_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margem_padrao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margem_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margem_competicao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Tipo de Anúncio ML',
                'verbose_name_plural': 'Configurações de Tipo de Anúncio ML',
                'ordering': ['tipo_anuncio', 'tipo_logistico', 'catalogo'],
                'unique_together': {('tipo_anuncio', 'tipo_logistico', 'catalogo')},
            },
        ),
    ]
