# Generated by Django 6.0.6 on 2026-07-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0013_configuracaomercadolivre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='comportamento_ativo',
            field=models.CharField(choices=[('padrao', 'Padrão (equilíbrio)'), ('busca_lucro', 'Busca-Lucro (maior margem)'), ('disputa', 'Disputa (ganha catálogo a qualquer custo seguro)')], default='padrao', max_length=20),
        ),
        migrations.CreateModel(
            name='PromocaoMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_externa', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SMART', 'Smart'), ('LIGHTNING', 'Lightning'), ('PRICE_DISCOUNT', 'Price Discount'), ('DEAL', 'Deal')], max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('started', 'Ativa'), ('candidate', 'Candidata')], max_length=20)),
                ('preco_original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_avaliado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meli_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('seller_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inicio_vigencia', models.DateTimeField(blank=True, null=True)),
                ('fim_vigencia', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='mercado_livre.variacaoanunciomercadolivre')),
            ],
            options={
                'verbose_name': 'Promoção Mercado Livre',
                'verbose_name_plural': 'Promoções Mercado Livre',
                'unique_together': {('variacao', 'chave_externa')},
            },
        ),
        migrations.CreateModel(
            name='RecomendacaoPrecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comportamento', models.CharField(choices=[('padrao', 'Padrão (equilíbrio)'), ('busca_lucro', 'Busca-Lucro (maior margem)'), ('disputa', 'Disputa (ganha catálogo a qualquer custo seguro)')], max_length=20)),
                ('tem_escolha', models.BooleanField(default=False)),
                ('cenario_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('cenario_tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('preco_recomendado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margem_recomendada', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bucket_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('exige_aprovacao', models.BooleanField(default=False)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='mercado_livre.variacaoanunciomercadolivre')),
            ],
            options={
                'verbose_name': 'Recomendação de Precificação',
                'verbose_name_plural': 'Recomendações de Precificação',
                'unique_together': {('variacao', 'comportamento')},
            },
        ),
    ]
