# Generated by Django 6.0.6 on 2026-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0014_variacaoanunciomercadolivre_comportamento_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacaoprecificacao',
            name='categoria_estado',
            field=models.CharField(blank=True, choices=[('sem_oportunidade', 'Sem oportunidade'), ('candidato', 'Candidato a participar'), ('oportunidade_troca', 'Oportunidade de troca'), ('otimizado', 'Otimizado — nada a fazer'), ('conflito_multiplas_ativas', 'Conflito — múltiplas promoções ativas')], max_length=30, null=True),
        ),
    ]
