# Generated by Django 6.0.6 on 2026-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0015_recomendacaoprecificacao_categoria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacaoprecificacao',
            name='categoria_estado',
            field=models.CharField(blank=True, choices=[('sem_oportunidade', 'Sem oportunidade'), ('candidato', 'Candidato a participar'), ('sugestao_risco', 'Sugestão de risco'), ('oportunidade_troca', 'Oportunidade de troca'), ('otimizado', 'Otimizado — nada a fazer'), ('operando_em_risco', 'Operando em risco'), ('conflito_multiplas_ativas', 'Conflito — múltiplas promoções ativas')], max_length=30, null=True),
        ),
    ]
