# Generated by Django 6.0.6 on 2026-07-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0016_alter_recomendacaoprecificacao_categoria_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacaoprecificacao',
            name='variacao_margem_pp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='margem_atual_vs_original_pp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
