# Generated by Django 6.0.6 on 2026-07-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0017_recomendacaoprecificacao_variacao_margem_pp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaotipoanunciomercadolivre',
            options={'ordering': ['tipo_anuncio'], 'verbose_name': 'Configuração de Tipo de Anúncio ML', 'verbose_name_plural': 'Configurações de Tipo de Anúncio ML'},
        ),
        migrations.AlterUniqueTogether(
            name='configuracaotipoanunciomercadolivre',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='configuracaotipoanunciomercadolivre',
            name='tipo_anuncio',
            field=models.CharField(choices=[('gold_special', 'Clássico'), ('gold_pro', 'Premium')], max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='configuracaotipoanunciomercadolivre',
            name='acrescimo_preco',
        ),
        migrations.RemoveField(
            model_name='configuracaotipoanunciomercadolivre',
            name='catalogo',
        ),
        migrations.RemoveField(
            model_name='configuracaotipoanunciomercadolivre',
            name='tipo_logistico',
        ),
    ]
