# Generated by Django 6.0.6 on 2026-07-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0018_alter_configuracaotipoanunciomercadolivre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='frete_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='frete_real_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
