# Generated by Django 6.0.6 on 2026-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0021_remover_config_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='altura_ordenada_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='comprimento_ordenada_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='largura_ordenada_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='situacao_dimensao_envio',
            field=models.CharField(blank=True, choices=[('iguais', 'Dimensões de envio iguais'), ('divergente', 'Divergência nas dimensões de envio'), ('nao_refletida_ml', 'Dimensão de envio não refletida no ML'), ('nao_salva_erp', 'Dimensão de envio não salva no ERP'), ('sem_dado_nenhum_lado', 'Sem dado de envio em nenhum dos 2 lados'), ('sem_produto_vinculado', 'Sem produto vinculado no ERP')], max_length=25, null=True),
        ),
    ]
