# Generated by Django 6.0.6 on 2026-08-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0022_variacaoanunciomercadolivre_altura_ordenada_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciomercadolivre',
            name='fotos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
