# Generated by Django 6.0.6 on 2026-08-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0023_anunciomercadolivre_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='mlbu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
