# Generated by Django 6.0.6 on 2026-09-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0025_variacaoanunciomercadolivre_frete_real_detalhamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDumpCategoriasMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerado_em_ml', models.DateTimeField(help_text='Valor do header X-Content-Created retornado pelo ML na última baixa.')),
                ('md5', models.CharField(help_text='Valor do header X-Content-MD5 retornado pelo ML na última baixa.', max_length=64)),
                ('total_categorias', models.PositiveIntegerField()),
                ('baixado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaMercadoLivre',
            fields=[
                ('category_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('categoria_raiz_id', models.CharField(db_index=True, max_length=20)),
                ('nivel', models.PositiveSmallIntegerField(help_text='Profundidade na árvore (tamanho do path_from_root).')),
                ('caminho_completo', models.CharField(help_text="Ex: 'Casa, Móveis e Decoração > Camas, Colchões e Acessórios > Conjuntos de Box e Colchão'.", max_length=500)),
                ('e_folha', models.BooleanField(default=True, help_text='True quando children_categories vem vazio — só categoria folha aceita anúncio.')),
                ('aceita_novo_anuncio', models.BooleanField(default=True)),
                ('status_categoria', models.CharField(blank=True, max_length=30)),
                ('tipo_atributos', models.CharField(blank=True, max_length=20)),
                ('condicoes_aceitas', models.JSONField(blank=True, default=list)),
                ('preco_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vertical', models.CharField(blank=True, max_length=50, null=True)),
                ('limite_titulo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('limite_subtitulo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('limite_descricao', models.PositiveIntegerField(blank=True, null=True)),
                ('limite_fotos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('limite_fotos_variacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('limite_variacoes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('catalog_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='mercado_livre.categoriamercadolivre')),
            ],
            options={
                'indexes': [models.Index(fields=['categoria_raiz_id'], name='mercado_liv_categor_4029e6_idx'), models.Index(fields=['nome'], name='mercado_liv_nome_8b4d18_idx')],
            },
        ),
    ]
