# Generated by Django 6.0.6 on 2026-09-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0026_estadodumpcategoriasmercadolivre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variacoes_anuncio', to='mercado_livre.categoriamercadolivre'),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='comissao_real_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='comissao_real_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='comissao_real_preco_usado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='comissao_real_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
