# Generated by Django 6.0.6 on 2026-09-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0028_categoriamercadolivre_comissao_media_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freteml',
            options={'ordering': ['peso_min', 'preco_min', '-regime'], 'verbose_name': 'Frete ML', 'verbose_name_plural': 'Fretes ML'},
        ),
        migrations.AddField(
            model_name='freteml',
            name='regime',
            field=models.CharField(choices=[('sem_frete_gratis_rapido', 'Sem Frete Grátis Rápido'), ('com_frete_gratis_rapido', 'Com Frete Grátis Rápido')], default='sem_frete_gratis_rapido', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='freteml',
            constraint=models.UniqueConstraint(fields=('peso_min', 'preco_min', 'regime'), name='frete_ml_peso_preco_regime_unico'),
        ),
    ]
