# Generated by Django 6.0.6 on 2026-10-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0029_alter_freteml_options_freteml_regime_and_more'),
        ('produtos', '0012_produto_comissao_media_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciomercadolivre',
            name='atributos_ml',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anunciomercadolivre',
            name='atributos_ml_lido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='atributos_ml',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AtributoCategoriaMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo_id', models.CharField(max_length=60)),
                ('nome', models.CharField(max_length=255)),
                ('tipo_valor', models.CharField(blank=True, max_length=30)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('tamanho_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('unidades_permitidas', models.JSONField(blank=True, null=True)),
                ('unidade_padrao', models.CharField(blank=True, max_length=30, null=True)),
                ('opcoes', models.JSONField(blank=True, null=True)),
                ('lido_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='mercado_livre.categoriamercadolivre')),
            ],
            options={
                'verbose_name': 'Atributo de Categoria Mercado Livre',
                'verbose_name_plural': 'Atributos de Categoria Mercado Livre',
                'ordering': ['nome'],
                'unique_together': {('categoria', 'atributo_id')},
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaProdutoMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo_id', models.CharField(max_length=60)),
                ('valor_id', models.CharField(blank=True, max_length=60, null=True)),
                ('valor_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unidade', models.CharField(blank=True, max_length=30, null=True)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado')], default='rascunho', max_length=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_mercado_livre', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Característica de Produto Mercado Livre',
                'verbose_name_plural': 'Características de Produto Mercado Livre',
                'ordering': ['atributo_id'],
                'unique_together': {('produto', 'atributo_id')},
            },
        ),
    ]
