# Generated by Django 6.0.6 on 2026-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0030_anunciomercadolivre_atributos_ml_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarreduraCaracteristicasMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('rodando', 'Rodando'), ('concluida', 'Concluída'), ('com_falhas', 'Concluída com falhas'), ('erro', 'Interrompida por erro')], default='rodando', max_length=12)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('total_anuncios', models.PositiveIntegerField(default=0)),
                ('anuncios_lidos', models.PositiveIntegerField(default=0)),
                ('total_categorias', models.PositiveIntegerField(default=0)),
                ('categorias_lidas', models.PositiveIntegerField(default=0)),
                ('falhas', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Varredura de Características Mercado Livre',
                'verbose_name_plural': 'Varreduras de Características Mercado Livre',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='atributocategoriamercadolivre',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Atributo de Categoria Mercado Livre', 'verbose_name_plural': 'Atributos de Categoria Mercado Livre'},
        ),
        migrations.RemoveField(
            model_name='atributocategoriamercadolivre',
            name='unidade_padrao',
        ),
        migrations.RemoveField(
            model_name='variacaoanunciomercadolivre',
            name='atributos_ml',
        ),
        migrations.AddField(
            model_name='anunciomercadolivre',
            name='atributos_ml_categoria_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='anunciomercadolivre',
            name='atributos_ml_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atributocategoriamercadolivre',
            name='componente',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='atributocategoriamercadolivre',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atributocategoriamercadolivre',
            name='permite_valor_proprio',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
