# Generated by Django 6.0.6 on 2026-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0031_varreduracaracteristicasmercadolivre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaFullMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40)),
                ('consultado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('arquivo_gerado_em', models.CharField(blank=True, max_length=40)),
                ('registros_arquivo', models.JSONField(blank=True, default=list)),
                ('estoque', models.JSONField(blank=True, default=dict)),
                ('reposicao', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Consulta Full Mercado Livre',
                'verbose_name_plural': 'Consultas Full Mercado Livre',
                'ordering': ['-consultado_em'],
            },
        ),
        migrations.CreateModel(
            name='CampoFullMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=10)),
                ('caminho', models.CharField(max_length=120)),
                ('nome_interno', models.CharField(blank=True, max_length=120)),
                ('situacao', models.CharField(choices=[('a_validar', 'A validar'), ('hipotese', 'Hipótese'), ('valido', 'Válido'), ('invalido', 'Inválido')], default='a_validar', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Campo Full Mercado Livre',
                'verbose_name_plural': 'Campos Full Mercado Livre',
                'ordering': ['fonte', 'caminho'],
                'unique_together': {('fonte', 'caminho')},
            },
        ),
    ]
