# Generated by Django 6.0.6 on 2026-10-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0032_consultafullmercadolivre_campofullmercadolivre'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoanunciomercadolivre',
            name='inventory_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
