# Generated by Django 6.0.6 on 2026-08-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacaoXmlManifestoNotaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial_cobertura', models.DateField(blank=True, null=True)),
                ('data_final_cobertura', models.DateField(blank=True, null=True)),
                ('data_ultima_chamada', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('sincronizado', 'Sincronizado'), ('falha', 'Falha ao sincronizar')], max_length=20)),
                ('motivo_da_falha', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sincronização do Manifesto de Nota de Entrada (XML)',
                'verbose_name_plural': 'Sincronização do Manifesto de Nota de Entrada (XML)',
            },
        ),
    ]
