# Generated by Django 6.0.6 on 2026-07-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAmazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=13, help_text='Comissão flat da Amazon (referral fee), em %.', max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Amazon',
                'verbose_name_plural': 'Configuração Amazon',
            },
        ),
    ]
