# Generated by Django 6.0.6 on 2026-07-13 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercado_livre', '0017_recomendacaoprecificacao_variacao_margem_pp_and_more'),
        ('produtos', '0003_produto_armazenagem_planilha'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePrecificacaoML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_alvo', models.CharField(choices=[('minima', 'Mínima'), ('padrao', 'Padrão'), ('competicao', 'Competição'), ('maxima', 'Máxima')], max_length=12)),
                ('preco_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_percentual_obtida', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_precificacao_ml', to='produtos.produto')),
                ('tipo_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_precificacao', to='mercado_livre.configuracaotipoanunciomercadolivre')),
            ],
            options={
                'unique_together': {('produto', 'tipo_anuncio', 'margem_alvo')},
            },
        ),
    ]
