# Generated by Django 6.0.6 on 2026-07-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='detalhamento',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
