# Generated by Django 6.0.6 on 2026-07-15 02:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0002_gradeprecificacaoml_detalhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeprecificacaoml',
            name='detalhamento',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
