# Generated by Django 6.0.6 on 2026-07-15 22:36

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_livre', '0019_variacaoanunciomercadolivre_frete_real_and_more'),
        ('precificacao', '0003_alter_gradeprecificacaoml_detalhamento'),
        ('produtos', '0003_produto_armazenagem_planilha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeprecificacaoml',
            options={'verbose_name': 'Grade de Precificação ML', 'verbose_name_plural': 'Grade de Precificação ML'},
        ),
        migrations.RenameField(
            model_name='gradeprecificacaoml',
            old_name='detalhamento',
            new_name='classico_detalhamento',
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_precificacao_ml', to='mercado_livre.variacaoanunciomercadolivre'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeprecificacaoml',
            unique_together={('produto', 'variacao')},
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='classico_competicao_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='classico_competicao_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='classico_maxima_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='classico_maxima_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='classico_minima_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='classico_minima_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='classico_padrao_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='classico_padrao_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='frete_classico_origem',
            field=models.CharField(blank=True, choices=[('tabela', 'Tabela'), ('real', 'Real (API)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='frete_classico_usado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='frete_premium_origem',
            field=models.CharField(blank=True, choices=[('tabela', 'Tabela'), ('real', 'Real (API)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='frete_premium_usado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_competicao_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_competicao_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_detalhamento',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_maxima_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_maxima_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_minima_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_minima_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_padrao_margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='premium_padrao_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='gradeprecificacaoml',
            name='margem_alvo',
        ),
        migrations.RemoveField(
            model_name='gradeprecificacaoml',
            name='margem_percentual_obtida',
        ),
        migrations.RemoveField(
            model_name='gradeprecificacaoml',
            name='preco_calculado',
        ),
        migrations.RemoveField(
            model_name='gradeprecificacaoml',
            name='tipo_anuncio',
        ),
    ]
