# Generated by Django 6.0.6 on 2026-07-19 01:10

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0010_gradeprecificacaoshopee'),
        ('produtos', '0004_rename_altura_produto_altura_produto_sem_embalar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaComissaoTiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adicional_fixo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Faixa de Comissão TikTok Shop',
                'verbose_name_plural': 'Faixas de Comissão TikTok Shop',
                'ordering': ['preco_min'],
            },
        ),
        migrations.CreateModel(
            name='GradePrecificacaoTiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sem_afiliado', 'Sem Afiliado'), ('com_afiliado', 'Com Afiliado')], max_length=15)),
                ('margem', models.CharField(choices=[('minima', 'Mínima'), ('padrao', 'Padrão'), ('maxima', 'Máxima'), ('competicao', 'Competição')], max_length=12)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margem_percentual_obtida', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('frete_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalhamento', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_precificacao_tiktok', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Grade de Precificação TikTok Shop',
                'verbose_name_plural': 'Grade de Precificação TikTok Shop',
                'unique_together': {('produto', 'tipo', 'margem')},
            },
        ),
    ]
