# Generated by Django 6.0.6 on 2026-07-19 05:09

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0011_tabelacomissaotiktok_gradeprecificacaotiktok'),
        ('produtos', '0004_rename_altura_produto_altura_produto_sem_embalar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreteAmazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dba', 'DBA (logística própria)'), ('fba', 'FBA (Amazon guarda e despacha)')], max_length=3)),
                ('peso_min', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('peso_max', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Faixa de Frete Amazon',
                'verbose_name_plural': 'Faixas de Frete Amazon',
                'ordering': ['tipo', 'preco_min', 'peso_min'],
            },
        ),
        migrations.CreateModel(
            name='TaxaKgAdicionalAmazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dba', 'DBA'), ('fba', 'FBA')], max_length=3)),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_por_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Taxa de Kg Adicional Amazon',
                'verbose_name_plural': 'Taxas de Kg Adicional Amazon',
                'ordering': ['tipo', 'preco_min'],
            },
        ),
        migrations.CreateModel(
            name='GradePrecificacaoAmazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dba', 'DBA'), ('fba', 'FBA')], max_length=3)),
                ('margem', models.CharField(choices=[('minima', 'Mínima'), ('padrao', 'Padrão'), ('maxima', 'Máxima'), ('competicao', 'Competição')], max_length=12)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margem_percentual_obtida', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('frete_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalhamento', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_precificacao_amazon', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Grade de Precificação Amazon',
                'verbose_name_plural': 'Grade de Precificação Amazon',
                'unique_together': {('produto', 'tipo', 'margem')},
            },
        ),
    ]
