# Generated by Django 6.0.6 on 2026-07-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0012_freteamazon_taxakgadicionalamazon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeprecificacaotiktok',
            name='preco_de_exibicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
