# Generated by Django 6.0.6 on 2026-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0013_gradeprecificacaotiktok_preco_de_exibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='motivo_nao_resolvida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='resolvida',
            field=models.BooleanField(default=True),
        ),
    ]
