# Generated by Django 6.0.6 on 2026-09-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0014_gradeprecificacaoml_motivo_nao_resolvida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='frete_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='frete_real_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='origem_frete',
            field=models.CharField(blank=True, choices=[('api_real', 'API Real'), ('tabela_calculada', 'Tabela Calculada')], max_length=20, null=True),
        ),
    ]
