# Generated by Django 6.0.6 on 2026-09-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0015_gradeprecificacaoml_frete_calculado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeprecificacaoml',
            name='frete_real_atualizado_em',
        ),
    ]
