# Generated by Django 6.0.6 on 2026-09-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0016_remove_gradeprecificacaoml_frete_real_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='comissao_calculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeprecificacaoml',
            name='origem_comissao',
            field=models.CharField(blank=True, choices=[('api_real', 'API Real'), ('config_aproximada', 'Config Aproximada')], max_length=20, null=True),
        ),
    ]
