"""
Django settings for projeto_sistema_interno_mb_sv project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

AGENTE_TOKEN = os.getenv('AGENTE_TOKEN')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'produtos',
    'marketplaces',
    'mercado_livre',
    'magalu',
    'raia',
    'shopee',
    'tiktok',
    'amazon',
    'precificacao',
    'agenda_videos',
    'api',
    'integracao_sysemp',
    'impostos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # * [EXPLICAÇÃO] → Decide qual banco (Magazine/Samvale) esta requisição
    #                  usa. Precisa vir ANTES do AuthenticationMiddleware,
    #                  que já busca request.user no banco certo.
    'core.middleware.EmpresaMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
    # * [EXPLICAÇÃO] → Middleware customizado de autenticação global. Controla o acesso a todas as rotas do sistema.
    'core.middleware.AutenticacaoMiddleware',
]


ROOT_URLCONF = 'projeto_sistema_interno_mb_sv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.empresa_ativa',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto_sistema_interno_mb_sv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# * [IMPORTANTE] → Credenciais do banco vêm do .env — nunca hardcode aqui
# * [EXPLICAÇÃO] → Usamos MySQL com charset utf8mb4 para suporte completo
# *                a caracteres especiais e acentos do português
# * [EXPLICAÇÃO] → 2 bancos permanentes, nomes fixos (decidido 17/08/2026)
#                  — não vêm mais de variável de ambiente, já que não
#                  mudam. 'default' aponta pra 'magazine' só como rede de
#                  segurança (qualquer coisa que ignore o Router cai aqui,
#                  em vez de quebrar) — na prática, o EmpresaRouter decide
#                  tudo, 'default' quase nunca é usado de verdade.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sistema_interno_magazine',
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    'magazine': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sistema_interno_magazine',
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    'samvale': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sistema_interno_samvale',
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
}

DATABASE_ROUTERS = ['core.database_router.EmpresaRouter']

GOOGLE_DRIVE_CREDENCIAIS_JSON = os.getenv('GOOGLE_DRIVE_CREDENCIAIS_JSON')

# * [EXPLICAÇÃO] → Achado real (18/08/2026): a credencial é a MESMA pras 2
#                  empresas (mesma conta Google, mesma API) — só a pasta
#                  raiz muda. "Magazine Estruturada" e "Samvale Estruturada"
#                  já existem como 2 pastas separadas dentro dessa mesma
#                  conta. Resolução por empresa mora em
#                  agenda_videos/funcoes_auxiliares/drive/cliente.py
#                  (obter_pasta_raiz_id_ativa), nunca lida direto daqui.
GOOGLE_DRIVE_PASTA_RAIZ_MAGAZINE = os.getenv('GOOGLE_DRIVE_PASTA_RAIZ_MAGAZINE')
GOOGLE_DRIVE_PASTA_RAIZ_SAMVALE = os.getenv('GOOGLE_DRIVE_PASTA_RAIZ_SAMVALE')

# Pastas de teste (18/08/2026) — fora da árvore real, criadas de propósito
# pra nenhum teste/diagnóstico nunca precisar escrever dentro de
# "Magazine Estruturada"/"Samvale Estruturada" de verdade.
GOOGLE_DRIVE_PASTA_TESTE_MAGAZINE = os.getenv('GOOGLE_DRIVE_PASTA_TESTE_MAGAZINE')
GOOGLE_DRIVE_PASTA_TESTE_SAMVALE = os.getenv('GOOGLE_DRIVE_PASTA_TESTE_SAMVALE')

# * [EXPLICAÇÃO] → Achado real (18/08/2026): Service Account tem SEMPRE 0
#                  bytes de cota própria (regra da plataforma Google, não
#                  configurável) — upload de conteúdo novo (diferente de
#                  criar pasta, que é só metadado) sempre falhava com
#                  storageQuotaExceeded, mesmo com permissão de editor.
#                  Conta é Google comum (sem Workspace), então Shared
#                  Drive de verdade e delegação de domínio não são opção.
#                  Escrita passa a autenticar como o USUÁRIO REAL dono do
#                  Drive (OAuth), via token gerado 1x por
#                  autorizar_drive_oauth.py — usa a cota dele, de verdade.
GOOGLE_DRIVE_OAUTH_CLIENT_SECRET_JSON = os.getenv('GOOGLE_DRIVE_OAUTH_CLIENT_SECRET_JSON')
GOOGLE_DRIVE_OAUTH_TOKEN_JSON = os.getenv('GOOGLE_DRIVE_OAUTH_TOKEN_JSON')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# * [EXPLICAÇÃO] → Configurado para português brasileiro e fuso de São Paulo
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# * [RESUMO] → Configuração de logging do sistema.
#              Exibe logs no terminal durante desenvolvimento.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        # * [EXPLICAÇÃO] → Formato padrão com timestamp, nível e mensagem.
        'padrao': {
            'format': '[{asctime}] {levelname} {name} → {message}',
            'style': '{',
            'datefmt': '%d/%m/%Y %H:%M:%S',
        },
    },

    'handlers': {
        # * [EXPLICAÇÃO] → Exibe os logs no terminal (stdout).
        'terminal': {
            'class': 'logging.StreamHandler',
            'formatter': 'padrao',
        },
    },

    'loggers': {
        # * [EXPLICAÇÃO] → Logger do app anuncios — captura signals e cálculos.
        'anuncios': {
            'handlers': ['terminal'],
            'level': 'INFO',
            'propagate': False,
        },
        # * [EXPLICAÇÃO] → Logger raiz — captura logs de todos os outros módulos.
        '': {
            'handlers': ['terminal'],
            'level': 'WARNING',
        },
    },
}