"""
Django settings for projeto_sistema_interno_mb_sv project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'produtos',
    'marketplaces',
    'mercado_livre',
    'magalu',
    'raia',
    'shopee',
    'tiktok',
    'precificacao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
    # * [EXPLICAÇÃO] → Middleware customizado de autenticação global. Controla o acesso a todas as rotas do sistema.
    'core.middleware.AutenticacaoMiddleware',
]


ROOT_URLCONF = 'projeto_sistema_interno_mb_sv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto_sistema_interno_mb_sv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# * [IMPORTANTE] → Credenciais do banco vêm do .env — nunca hardcode aqui
# * [EXPLICAÇÃO] → Usamos MySQL com charset utf8mb4 para suporte completo
# *                a caracteres especiais e acentos do português
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# * [EXPLICAÇÃO] → Configurado para português brasileiro e fuso de São Paulo
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# * [RESUMO] → Configuração de logging do sistema.
#              Exibe logs no terminal durante desenvolvimento.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        # * [EXPLICAÇÃO] → Formato padrão com timestamp, nível e mensagem.
        'padrao': {
            'format': '[{asctime}] {levelname} {name} → {message}',
            'style': '{',
            'datefmt': '%d/%m/%Y %H:%M:%S',
        },
    },

    'handlers': {
        # * [EXPLICAÇÃO] → Exibe os logs no terminal (stdout).
        'terminal': {
            'class': 'logging.StreamHandler',
            'formatter': 'padrao',
        },
    },

    'loggers': {
        # * [EXPLICAÇÃO] → Logger do app anuncios — captura signals e cálculos.
        'anuncios': {
            'handlers': ['terminal'],
            'level': 'INFO',
            'propagate': False,
        },
        # * [EXPLICAÇÃO] → Logger raiz — captura logs de todos os outros módulos.
        '': {
            'handlers': ['terminal'],
            'level': 'WARNING',
        },
    },
}