# Generated by Django 6.0.6 on 2026-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Marketplace', 'verbose_name_plural': 'Marketplaces'},
        ),
        migrations.AddField(
            model_name='marketplace',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
